apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: harbor
resources:
  - namespace.yaml
  - release.yaml
  - repository.yaml
  - cloudflare.yaml
  - secrets.yaml
  - certificate.yaml
  - bootstrap-configmap.yaml
  - bootstrap-job.yaml

configMapGenerator:
  - name: harbor-values
    files:
      - values.yaml=values.yaml

configurations:
  - kustomizeconfig.yaml
