apiVersion: v1
kind: ConfigMap
metadata:
  name: social-to-mealie-configmap
data:
  OPENAI_URL: https://api.openai.com/v1
  TRANSCRIPTION_MODEL: whisper-1
  TEXT_MODEL: gpt-4o-mini
  MEALIE_URL: https://mealie.bde-dev.net
